[general]
import = [
    "~/.config/alacritty/light-theme.toml"
]

[window]
startup_mode = "Maximized"

[font]
normal = {family = "Fira Code Retina", style = "Regular"}
size = 9
offset = {x = 0, y = 3}

[selection]
save_to_clipboard = true

[cursor]
style = {shape="Block"}
thickness = 0.40

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    {mods = "Control | Shift", key = "+", action = "IncreaseFontSize"},
    {mods = "Alt", key = "F2", command = { program = "sed", args = [
        "--in-place",
        """
            s:dark-them\u0065:dark-disabled-them\u0065:
            s:light-them\u0065:dark-them\u0065:
            s:dark-disabled-them\u0065:light-them\u0065:
        """,
        "/home/adam/.config/alacritty/alacritty.toml"
    ] }},
]
