import = [
    "~/.config/alacritty/dark-theme.toml"
    #"~/.config/alacritty/light-theme.toml"
]

[window]
startup_mode = "Maximized"

[font]
normal = {family = "Fira Code Retina", style = "Regular"}
size = 9
offset = {x = 0, y = 3}

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t."
save_to_clipboard = true

[cursor]
style = {shape="Block"}
thickness = 0.40

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    {key="F11", action="ToggleFullscreen"}
]
